-- Remediate Supabase advisor findings: safe first pass.
-- Adds missing FK indexes, removes duplicate indexes, and tightens direct execute grants on trigger/legacy RPC helpers.

-- Unindexed foreign keys
create index if not exists "idx_ai_knowledge_items_pack_id_fk" on "public"."ai_knowledge_items" ("pack_id");
create index if not exists "idx_ai_knowledge_packs_owner_user_id_fk" on "public"."ai_knowledge_packs" ("owner_user_id");
create index if not exists "idx_ai_persona_knowledge_packs_pack_id_fk" on "public"."ai_persona_knowledge_packs" ("pack_id");
create index if not exists "idx_ai_personas_default_audience_variant_id_fk" on "public"."ai_personas" ("default_audience_variant_id");
create index if not exists "idx_ai_personas_default_soundbyte_id_fk" on "public"."ai_personas" ("default_soundbyte_id");
create index if not exists "idx_ai_personas_owner_user_id_fk" on "public"."ai_personas" ("owner_user_id");
create index if not exists "idx_assembly_agenda_item_meeting_id_fk" on "public"."assembly_agenda_item" ("meeting_id");
create index if not exists "idx_assembly_agenda_item_memo_id_fk" on "public"."assembly_agenda_item" ("memo_id");
create index if not exists "idx_assembly_attendance_meeting_id_fk" on "public"."assembly_attendance" ("meeting_id");
create index if not exists "idx_assembly_attendance_user_id_fk" on "public"."assembly_attendance" ("user_id");
create index if not exists "idx_assembly_handoff_outcome_id_fk" on "public"."assembly_handoff" ("outcome_id");
create index if not exists "idx_assembly_meeting_chair_id_fk" on "public"."assembly_meeting" ("chair_id");
create index if not exists "idx_assembly_memo_author_id_fk" on "public"."assembly_memo" ("author_id");
create index if not exists "idx_assembly_outcome_agenda_item_id_fk" on "public"."assembly_outcome" ("agenda_item_id");
create index if not exists "idx_assembly_outcome_meeting_id_fk" on "public"."assembly_outcome" ("meeting_id");
create index if not exists "idx_assembly_outcome_memo_id_fk" on "public"."assembly_outcome" ("memo_id");
create index if not exists "idx_assembly_outcome_owner_id_fk" on "public"."assembly_outcome" ("owner_id");
create index if not exists "idx_assembly_resolution_meeting_id_fk" on "public"."assembly_resolution" ("meeting_id");
create index if not exists "idx_assembly_review_meeting_id_fk" on "public"."assembly_review" ("meeting_id");
create index if not exists "idx_boh_app_parent_app_id_fk" on "public"."boh_app" ("parent_app_id");
create index if not exists "idx_boh_change_request_reviewed_by_fk" on "public"."boh_change_request" ("reviewed_by");
create index if not exists "idx_boh_initiative_locked_by_fk" on "public"."boh_initiative" ("locked_by");
create index if not exists "idx_boh_initiative_priority_id_fk" on "public"."boh_initiative" ("priority_id");
create index if not exists "idx_boh_initiative_status_id_fk" on "public"."boh_initiative" ("status_id");
create index if not exists "idx_boh_notification_contact_preference_patron_organisation_" on "public"."boh_notification_contact_preference" ("patron_organisation_id");
create index if not exists "idx_boh_notification_contact_preference_patron_person_id_fk" on "public"."boh_notification_contact_preference" ("patron_person_id");
create index if not exists "idx_boh_notification_event_contact_preference_id_fk" on "public"."boh_notification_event" ("contact_preference_id");
create index if not exists "idx_boh_notification_event_patron_organisation_id_fk" on "public"."boh_notification_event" ("patron_organisation_id");
create index if not exists "idx_boh_notification_event_patron_person_id_fk" on "public"."boh_notification_event" ("patron_person_id");
create index if not exists "idx_boh_sms_inbound_event_tenant_id_fk" on "public"."boh_sms_inbound_event" ("tenant_id");
create index if not exists "idx_boh_task_created_by_fk" on "public"."boh_task" ("created_by");
create index if not exists "idx_boh_task_comment_author_id_fk" on "public"."boh_task_comment" ("author_id");
create index if not exists "idx_boh_user_story_central_task_id_fk" on "public"."boh_user_story" ("central_task_id");
create index if not exists "idx_boh_user_story_created_by_fk" on "public"."boh_user_story" ("created_by");
create index if not exists "idx_boh_user_story_execution_dispatched_by_fk" on "public"."boh_user_story" ("execution_dispatched_by");
create index if not exists "idx_boh_user_story_forge_reviewed_by_fk" on "public"."boh_user_story" ("forge_reviewed_by");
create index if not exists "idx_boh_user_story_forge_status_id_fk" on "public"."boh_user_story" ("forge_status_id");
create index if not exists "idx_boh_user_story_module_id_fk" on "public"."boh_user_story" ("module_id");
create index if not exists "idx_boh_user_story_owner_user_id_fk" on "public"."boh_user_story" ("owner_user_id");
create index if not exists "idx_boh_user_story_priority_id_fk" on "public"."boh_user_story" ("priority_id");
create index if not exists "idx_boh_user_story_tablez_task_id_fk" on "public"."boh_user_story" ("tablez_task_id");
create index if not exists "idx_boh_user_story_event_changed_by_fk" on "public"."boh_user_story_event" ("changed_by");
create index if not exists "idx_boh_workstream_approval_reviewed_by_fk" on "public"."boh_workstream_approval" ("reviewed_by");
create index if not exists "idx_cellar_activity_events_actor_auth_user_id_fk" on "public"."cellar_activity_events" ("actor_auth_user_id");
create index if not exists "idx_cellar_activity_events_asset_id_fk" on "public"."cellar_activity_events" ("asset_id");
create index if not exists "idx_cellar_activity_events_prepared_qa_id_fk" on "public"."cellar_activity_events" ("prepared_qa_id");
create index if not exists "idx_cellar_asset_access_requests_asset_id_fk" on "public"."cellar_asset_access_requests" ("asset_id");
create index if not exists "idx_cellar_booking_link_audits_investor_session_id_fk" on "public"."cellar_booking_link_audits" ("investor_session_id");
create index if not exists "idx_cellar_investor_access_source_access_code_id_fk" on "public"."cellar_investor_access" ("source_access_code_id");
create index if not exists "idx_cellar_investor_profiles_patron_person_id_fk" on "public"."cellar_investor_profiles" ("patron_person_id");
create index if not exists "idx_cellar_investor_questions_investor_session_id_fk" on "public"."cellar_investor_questions" ("investor_session_id");
create index if not exists "idx_cellar_investor_questions_promoted_prepared_qa_id_fk" on "public"."cellar_investor_questions" ("promoted_prepared_qa_id");
create index if not exists "idx_cellar_investor_questions_related_asset_id_fk" on "public"."cellar_investor_questions" ("related_asset_id");
create index if not exists "idx_cellar_investor_sessions_guest_access_code_id_fk" on "public"."cellar_investor_sessions" ("guest_access_code_id");
create index if not exists "idx_cellar_messages_sender_auth_user_id_fk" on "public"."cellar_messages" ("sender_auth_user_id");
create index if not exists "idx_cellar_prepared_qa_related_asset_id_fk" on "public"."cellar_prepared_qa" ("related_asset_id");
create index if not exists "idx_cellar_prepared_qa_related_asset_id_fk" on "public"."cellar_prepared_qa" ("related_asset_id");
create index if not exists "idx_central_agent_actions_reviewed_by_fk" on "public"."central_agent_actions" ("reviewed_by");
create index if not exists "idx_central_agent_capability_bindings_created_by_fk" on "public"."central_agent_capability_bindings" ("created_by");
create index if not exists "idx_central_agent_capability_bindings_updated_by_fk" on "public"."central_agent_capability_bindings" ("updated_by");
create index if not exists "idx_central_agent_creation_requests_created_agent_id_fk" on "public"."central_agent_creation_requests" ("created_agent_id");
create index if not exists "idx_central_agent_creation_requests_persona_template_id_fk" on "public"."central_agent_creation_requests" ("persona_template_id");
create index if not exists "idx_central_agent_creation_requests_resolved_by_fk" on "public"."central_agent_creation_requests" ("resolved_by");
create index if not exists "idx_central_agent_model_route_model_key_fk" on "public"."central_agent_model_route" ("model_key");
create index if not exists "idx_central_agent_profile_documents_created_by_fk" on "public"."central_agent_profile_documents" ("created_by");
create index if not exists "idx_central_agent_profile_documents_updated_by_fk" on "public"."central_agent_profile_documents" ("updated_by");
create index if not exists "idx_central_agents_approved_by_fk" on "public"."central_agents" ("approved_by");
create index if not exists "idx_central_agents_model_key_fk" on "public"."central_agents" ("model_key");
create index if not exists "idx_central_agents_persona_template_id_fk" on "public"."central_agents" ("persona_template_id");
create index if not exists "idx_central_agents_vps_deployed_by_fk" on "public"."central_agents" ("vps_deployed_by");
create index if not exists "idx_central_credential_audit_events_actor_id_fk" on "public"."central_credential_audit_events" ("actor_id");
create index if not exists "idx_central_credentials_created_by_fk" on "public"."central_credentials" ("created_by");
create index if not exists "idx_central_credentials_updated_by_fk" on "public"."central_credentials" ("updated_by");
create index if not exists "idx_central_lessons_learned_created_by_fk" on "public"."central_lessons_learned" ("created_by");
create index if not exists "idx_central_lessons_learned_updated_by_fk" on "public"."central_lessons_learned" ("updated_by");
create index if not exists "idx_central_lessons_learned_verified_by_fk" on "public"."central_lessons_learned" ("verified_by");
create index if not exists "idx_central_models_created_by_fk" on "public"."central_models" ("created_by");
create index if not exists "idx_central_task_assigned_user_id_fk" on "public"."central_task" ("assigned_user_id");
create index if not exists "idx_central_task_qa_agent_runtime_id_fk" on "public"."central_task" ("qa_agent_runtime_id");
create index if not exists "idx_central_task_requested_by_fk" on "public"."central_task" ("requested_by");
create index if not exists "idx_central_task_source_story_id_fk" on "public"."central_task" ("source_story_id");
create index if not exists "idx_central_task_delivery_event_actor_agent_runtime_id_fk" on "public"."central_task_delivery_event" ("actor_agent_runtime_id");
create index if not exists "idx_central_task_delivery_event_actor_user_id_fk" on "public"."central_task_delivery_event" ("actor_user_id");
create index if not exists "idx_central_task_delivery_event_task_id_fk" on "public"."central_task_delivery_event" ("task_id");
create index if not exists "idx_central_task_dependency_created_by_fk" on "public"."central_task_dependency" ("created_by");
create index if not exists "idx_central_task_run_agent_runtime_id_fk" on "public"."central_task_run" ("agent_runtime_id");
create index if not exists "idx_central_task_run_model_key_fk" on "public"."central_task_run" ("model_key");
create index if not exists "idx_central_task_run_task_id_fk" on "public"."central_task_run" ("task_id");
create index if not exists "idx_content_blueprint_audience_variant_id_fk" on "public"."content_blueprint" ("audience_variant_id");
create index if not exists "idx_content_blueprint_owner_user_id_fk" on "public"."content_blueprint" ("owner_user_id");
create index if not exists "idx_content_blueprint_soundbyte_id_fk" on "public"."content_blueprint" ("soundbyte_id");
create index if not exists "idx_content_draft_created_by_user_id_fk" on "public"."content_draft" ("created_by_user_id");
create index if not exists "idx_content_draft_section_id_fk" on "public"."content_draft" ("section_id");
create index if not exists "idx_content_exchanges_section_id_fk" on "public"."content_exchanges" ("section_id");
create index if not exists "idx_content_projects_audience_variant_id_fk" on "public"."content_projects" ("audience_variant_id");
create index if not exists "idx_content_projects_interviewer_knowledge_pack_id_fk" on "public"."content_projects" ("interviewer_knowledge_pack_id");
create index if not exists "idx_content_projects_interviewer_persona_id_fk" on "public"."content_projects" ("interviewer_persona_id");
create index if not exists "idx_counter_ticket_requester_person_id_fk" on "public"."counter_ticket" ("requester_person_id");
create index if not exists "idx_forge_walkthrough_run_requested_by_fk" on "public"."forge_walkthrough_run" ("requested_by");
create index if not exists "idx_keep_file_folder_id_fk" on "public"."keep_file" ("folder_id");
create index if not exists "idx_keep_file_source_file_id_fk" on "public"."keep_file" ("source_file_id");
create index if not exists "idx_keep_file_uploaded_by_fk" on "public"."keep_file" ("uploaded_by");
create index if not exists "idx_keep_file_activity_file_id_fk" on "public"."keep_file_activity" ("file_id");
create index if not exists "idx_keep_file_activity_folder_id_fk" on "public"."keep_file_activity" ("folder_id");
create index if not exists "idx_keep_file_activity_user_id_fk" on "public"."keep_file_activity" ("user_id");
create index if not exists "idx_keep_file_approval_file_id_fk" on "public"."keep_file_approval" ("file_id");
create index if not exists "idx_keep_file_approval_requested_by_fk" on "public"."keep_file_approval" ("requested_by");
create index if not exists "idx_keep_file_approval_reviewed_by_fk" on "public"."keep_file_approval" ("reviewed_by");
create index if not exists "idx_keep_file_version_uploaded_by_fk" on "public"."keep_file_version" ("uploaded_by");
create index if not exists "idx_keep_folder_created_by_fk" on "public"."keep_folder" ("created_by");
create index if not exists "idx_keep_quick_link_created_by_fk" on "public"."keep_quick_link" ("created_by");
create index if not exists "idx_keep_user_access_access_granted_by_fk" on "public"."keep_user_access" ("access_granted_by");
create index if not exists "idx_keep_user_access_folder_id_fk" on "public"."keep_user_access" ("folder_id");
create index if not exists "idx_keep_user_access_user_id_fk" on "public"."keep_user_access" ("user_id");
create index if not exists "idx_keep_whiteboard_item_card_id_fk" on "public"."keep_whiteboard_item" ("card_id");
create index if not exists "idx_loft_external_profile_link_patron_organisation_id_fk" on "public"."loft_external_profile_link" ("patron_organisation_id");
create index if not exists "idx_loft_question_loft_room_id_fk" on "public"."loft_question" ("loft_room_id");
create index if not exists "idx_loft_video_session_created_by_fk" on "public"."loft_video_session" ("created_by");
create index if not exists "idx_loft_video_session_patron_organisation_id_fk" on "public"."loft_video_session" ("patron_organisation_id");
create index if not exists "idx_scheduling_blackout_dates_staff_id_fk" on "public"."scheduling_blackout_dates" ("staff_id");
create index if not exists "idx_scheduling_bookings_booking_account_staff_id_fk" on "public"."scheduling_bookings" ("booking_account_staff_id");
create index if not exists "idx_scheduling_bookings_meeting_type_id_fk" on "public"."scheduling_bookings" ("meeting_type_id");
create index if not exists "idx_scheduling_bookings_staff_id_fk" on "public"."scheduling_bookings" ("staff_id");
create index if not exists "idx_scheduling_email_events_booking_id_fk" on "public"."scheduling_email_events" ("booking_id");
create index if not exists "idx_scheduling_email_events_reminder_job_id_fk" on "public"."scheduling_email_events" ("reminder_job_id");
create index if not exists "idx_scheduling_shared_calendar_owners_created_by_user_id_fk" on "public"."scheduling_shared_calendar_owners" ("created_by_user_id");
create index if not exists "idx_tablez_chair_chair_role_id_fk" on "public"."tablez_chair" ("chair_role_id");
create index if not exists "idx_tablez_chair_assignment_history_performed_by_fk" on "public"."tablez_chair_assignment_history" ("performed_by");
create index if not exists "idx_tablez_chair_assignment_history_previous_user_id_fk" on "public"."tablez_chair_assignment_history" ("previous_user_id");
create index if not exists "idx_tablez_chair_move_request_current_chair_id_fk" on "public"."tablez_chair_move_request" ("current_chair_id");
create index if not exists "idx_tablez_chair_move_request_current_section_id_fk" on "public"."tablez_chair_move_request" ("current_section_id");
create index if not exists "idx_tablez_chair_move_request_current_table_id_fk" on "public"."tablez_chair_move_request" ("current_table_id");
create index if not exists "idx_tablez_chair_move_request_resolved_by_fk" on "public"."tablez_chair_move_request" ("resolved_by");
create index if not exists "idx_tablez_chair_move_request_target_chair_id_fk" on "public"."tablez_chair_move_request" ("target_chair_id");
create index if not exists "idx_tablez_chair_move_request_target_table_id_fk" on "public"."tablez_chair_move_request" ("target_table_id");

-- Duplicate indexes: keep canonical/constraint-backed names, drop duplicates.
drop index if exists public."idx_boh_initiative_status";
drop index if exists public."idx_boh_invite_invited_by";
drop index if exists public."idx_boh_user_app_unique";
drop index if exists public."cellar_investor_access_email_lower_idx";
drop index if exists public."idx_central_agents_parent";
drop index if exists public."idx_central_task_dispatch_state";
drop index if exists public."idx_central_task_governance_status";
drop index if exists public."idx_central_task_is_archived";
drop index if exists public."idx_content_sections_project_order";
drop index if exists public."idx_counter_ticket_duplicate_of";
drop index if exists public."idx_counter_ticket_priority";
drop index if exists public."idx_counter_ticket_release_version";
drop index if exists public."idx_counter_ticket_status";

-- Security advisor: trigger/legacy guest RPC helpers should not be directly executable through PostgREST.
-- Revoke from PUBLIC too; otherwise anon/authenticated inherit EXECUTE through PUBLIC.
revoke execute on function public.boh_touch_updated_at() from public, anon, authenticated;
revoke execute on function public.update_host_application_updated_at() from public, anon, authenticated;
revoke execute on function public.update_waitlist_updated_at() from public, anon, authenticated;
revoke execute on function public.set_assembly_updated_at() from public, anon, authenticated;
revoke execute on function public.check_guest_waitlist_status(text, text) from public, anon, authenticated;
revoke execute on function public.request_personal_room_access(text, text, text, text) from public, anon, authenticated;

-- Keep authenticated app-called/security-helper RPCs available, but remove anonymous direct execution.
revoke execute on function public.current_boh_tenant_id() from public, anon, authenticated;
revoke execute on function public.get_host_applications(text) from public, anon, authenticated;
revoke execute on function public.get_my_host_application_status() from public, anon, authenticated;
revoke execute on function public.get_quarterly_metrics(text, integer) from public, anon, authenticated;
revoke execute on function public.is_boh_staff() from public, anon, authenticated;
grant execute on function public.current_boh_tenant_id() to authenticated;
grant execute on function public.get_host_applications(text) to authenticated;
grant execute on function public.get_my_host_application_status() to authenticated;
grant execute on function public.get_quarterly_metrics(text, integer) to authenticated;
grant execute on function public.is_boh_staff() to authenticated;

-- Search path hardening
alter function public.set_assembly_updated_at() set search_path = public, pg_temp;

-- RLS enabled with no policies: make explicit deny-all policies so the no-policy advisor is cleared without broadening access.
drop policy if exists "deny all direct access" on public."google_calendar_sync";
create policy "deny all direct access" on public."google_calendar_sync" for all to anon, authenticated using (false) with check (false);
drop policy if exists "deny all direct access" on public."google_oauth_tokens";
create policy "deny all direct access" on public."google_oauth_tokens" for all to anon, authenticated using (false) with check (false);
